language: swift

matrix:
  include:
    - os: osx
      osx_image: xcode7.3

script:
  - xcrun swiftc --version
  - xctool -project EonilJSON.xcodeproj -scheme EonilJSON-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project EonilJSON.xcodeproj -scheme EonilJSON-iOS-Tests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
